/**
 * Copy the built game into the iOS app.
 *
 * The page is embedded as a JavaScript string rather than shipped as a file:
 * a WebView loading from a string needs no file access, no custom scheme and
 * no asset resolution, and what is verified locally is byte for byte what the
 * build uploads. `JSON.stringify` does the escaping, so nothing in the bundle
 * can break out of the literal.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const here = path.dirname(fileURLToPath(import.meta.url));
const app = path.resolve(here, '..');
const game = path.resolve(app, '..', 'polderland-phaser');

const source = path.join(game, 'dist-single', 'index.html');
if (!fs.existsSync(source)) {
  throw new Error(
    `${source} is missing. Run "npm run build && node scripts/build-single.mjs" in polderland-phaser first.`,
  );
}

const html = fs.readFileSync(source, 'utf8');
if (!html.includes('__polderland')) {
  throw new Error('the built page does not look like the game');
}

const out = path.join(app, 'src', 'gameHtml.js');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  `// Generated by scripts/sync-game.mjs. Do not edit.\n`
  + `// Source: polderland-phaser/dist-single/index.html\n`
  + `export default ${JSON.stringify(html)};\n`,
);

for (const [from, to] of [
  ['assets/icon.png', 'assets/icon.png'],
  ['assets/splash-icon.png', 'assets/splash-icon.png'],
]) {
  const src = path.join(game, from);
  if (fs.existsSync(src)) fs.copyFileSync(src, path.join(app, to));
}

const kb = (n) => `${(n / 1024).toFixed(0)} kB`;
console.log(`game synced: ${kb(html.length)} of HTML -> src/gameHtml.js`);
